### ISSUE TITLE
Explore performance uplift from pre-sorting

### ISSUE THREAD

**Issue by topher-lo** [neocortexdb/functime#16]
https://www.rhosignal.com/posts/polars-sorted-data-2/

**Comment by vienneraphael** [comment]
Do you mean that we try to compare:
- Basic computing without sorting
VS
- Sorting + using `.set_sorted()`?

**Comment by topher-lo** [comment]
Absolutely. I'd don't find crazy improvements in forecasting. But I think it'll benefit tsfresh.

**Comment by vienneraphael** [comment]
Here is the reproduction of the blog: there's definitely an improvement.
![image](https://github.com/neocortexdb/functime/assets/129849233/a464a30a-747b-4bd9-af45-460ddc497919)

Now i'm trying without a pre-sorted column to see if that's the same path under the hood

**Comment by vienneraphael** [comment]
However when we start from an unsorted column, sort it and use set_sorted on it, it doesn't work any longer:

![image](https://github.com/neocortexdb/functime/assets/129849233/afc9cd2b-91d3-4a8b-8213-b770cf75e2c1)

**Comment by vienneraphael** [comment]
Thinking about it more thoroughly, i think this really is a group_by optimization, where knowing the column is sorted has an impact. However, i wasn't able to find any features using group_by except `friedrich_coefficients`, which cannot be optimized since quantiles are not returned sorted by `x.qcut`.
I'll try to see if there are any functions where sorted or not matters.

**Comment by topher-lo** [comment]
Stale.

**Comment by topher-lo** [comment]
Stale
